<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Currency</name>
   <tag></tag>
   <elementGuidId>d759776e-89e2-42b2-8c0f-07f7245e4733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form-currency']/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-link.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;$ &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>553ae282-c7cf-44d8-96f1-b4e2b2ccd614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link dropdown-toggle</value>
      <webElementGuid>cdc1f262-ee4c-4126-b929-fd8edfc76eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>799f1e66-d33c-4ab6-80e6-76073333607a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                               $        Currency </value>
      <webElementGuid>7c821225-7ab5-4d22-a22f-993c6ab125c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-currency&quot;)/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-link dropdown-toggle&quot;]</value>
      <webElementGuid>b38074a3-eca9-4529-ad7e-efc7bfd3ebbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-currency']/div/button</value>
      <webElementGuid>383d88e3-79f8-4478-b01e-24fba3ee9fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9d802f08-251d-4041-8463-0b9b10154177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '                               $        Currency ' or . = '                               $        Currency ')]</value>
      <webElementGuid>c2d6093f-4dec-4a56-9e96-7668c707db34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
