<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ex Tax 500.00_img-fluid</name>
   <tag></tag>
   <elementGuidId>0dd912b9-22b4-436b-8058-738f2dd07ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;iPhone&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6a0d0b22-1d42-4603-acb4-7c05f6601dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://localhost/opencart41/upload/image/cache/catalog/demo/iphone_1-200x200.jpg</value>
      <webElementGuid>6af06173-8df0-4cbd-ba83-d40d28c697a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>iPhone</value>
      <webElementGuid>c8a4815b-1424-4050-89c3-2a7eac5fba33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>iPhone</value>
      <webElementGuid>a2d69e49-7417-45d7-b8ee-02ff07b6463c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>9bc29cbb-6de2-466f-b568-e06594cb23be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4&quot;]/div[@class=&quot;col mb-3&quot;]/div[@class=&quot;product-thumb&quot;]/div[@class=&quot;image&quot;]/a[1]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>5cd82251-032b-492a-a728-b61ac8167212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/div/div/a/img</value>
      <webElementGuid>92ac5b8d-a2b3-4445-ba7d-c9170d44277c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='iPhone']</value>
      <webElementGuid>b891ae51-792c-4be9-9a38-ebcc08c3c978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>9ad4ed48-9d36-4802-8eca-dde93af29851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://localhost/opencart41/upload/image/cache/catalog/demo/iphone_1-200x200.jpg' and @alt = 'iPhone' and @title = 'iPhone']</value>
      <webElementGuid>36c76379-dd83-49f9-9e6e-475e05e25be7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
