<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ex Tax 101.00_img-fluid</name>
   <tag></tag>
   <elementGuidId>9cb23cde-a2ef-4c58-9a7d-53390b1f2145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div[3]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Apple Cinema 30\&quot;&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>240d8471-65c4-4c49-9c3f-70ba01509b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://localhost/opencart41/upload/image/cache/catalog/demo/apple_cinema_30-200x200.jpg</value>
      <webElementGuid>6a844389-ec80-4faa-9073-881febcf519f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Apple Cinema 30&quot;</value>
      <webElementGuid>a28455f7-4d06-4836-88af-76472c5b23f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apple Cinema 30&quot;</value>
      <webElementGuid>48b8746a-5bac-4a50-8488-e680cc87b26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>64aec06c-2227-4a70-8f68-5e68789b8840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4&quot;]/div[@class=&quot;col mb-3&quot;]/div[@class=&quot;product-thumb&quot;]/div[@class=&quot;image&quot;]/a[1]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>dc943f56-e3ab-4d31-9029-0c2ce3bb8f73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[3]/div/div/a/img</value>
      <webElementGuid>994de58d-d054-4273-b77b-0ce03a64d9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Apple Cinema 30&quot;']</value>
      <webElementGuid>ec56fc39-d4b9-48e5-93d9-2dc43196400f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/img</value>
      <webElementGuid>f2a81e5c-dc6f-4c0b-8122-e05e87b73c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://localhost/opencart41/upload/image/cache/catalog/demo/apple_cinema_30-200x200.jpg' and @alt = 'Apple Cinema 30&quot;' and @title = 'Apple Cinema 30&quot;']</value>
      <webElementGuid>a0d53cf2-660f-429f-8857-858018c8e5f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
