<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Featured_img-fluid</name>
   <tag></tag>
   <elementGuidId>48d5016a-93f8-4fc4-86a7-30ce2d7c99d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.image > a > img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;MacBook&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eedef688-7ec6-42c0-82cb-788ef1b376f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://localhost/opencart41/upload/image/cache/catalog/demo/macbook_1-200x200.jpg</value>
      <webElementGuid>b8b1e447-049c-42f0-b361-93f346ab87f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MacBook</value>
      <webElementGuid>275032fa-494a-4126-b8b7-78adf92e594f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MacBook</value>
      <webElementGuid>cc006c49-2a41-48b6-b601-1bd0c7f4f291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>8be6139a-a26f-473e-ac85-307d5683cd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4&quot;]/div[@class=&quot;col mb-3&quot;]/div[@class=&quot;product-thumb&quot;]/div[@class=&quot;image&quot;]/a[1]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>6cdb94f9-e255-450d-a445-a51a86422a65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div/div/a/img</value>
      <webElementGuid>16aa2107-24cf-4df9-aabe-1792fabcba88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MacBook']</value>
      <webElementGuid>1dee3cf1-65c6-4246-9e83-2de61d1a034d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/img</value>
      <webElementGuid>0426d624-4a33-443d-835e-0563be810d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://localhost/opencart41/upload/image/cache/catalog/demo/macbook_1-200x200.jpg' and @alt = 'MacBook' and @title = 'MacBook']</value>
      <webElementGuid>6783166c-7307-4a51-973f-d4cc58527a8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
