<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Samsung SyncMaster 941BW</name>
   <tag></tag>
   <elementGuidId>01380b27-837a-467a-8ed0-4036ed6e406d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-list']/div[2]/div/div[2]/div/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Samsung SyncMaster 941BW&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f1c1093-d3d8-4a7a-beff-047ef5849072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost/opencart41/upload/index.php?route=product/product&amp;language=en-gb&amp;product_id=33&amp;path=25_28</value>
      <webElementGuid>f5d7dce9-7089-42e1-9016-d360dc0af3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samsung SyncMaster 941BW</value>
      <webElementGuid>c6b6e112-59f8-475c-adcd-1d2bf5b87b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-list&quot;)/div[@class=&quot;col mb-3&quot;]/div[@class=&quot;product-thumb&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;description&quot;]/h4[1]/a[1]</value>
      <webElementGuid>c899d82e-9ce4-44eb-8950-8814fdd6c39a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-list']/div[2]/div/div[2]/div/h4/a</value>
      <webElementGuid>0239dffd-7af7-4674-a8a9-71943e184fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Samsung SyncMaster 941BW')]</value>
      <webElementGuid>1216daf3-58f1-44de-a41e-198fcc6a5932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ex Tax: $100.00'])[1]/following::a[2]</value>
      <webElementGuid>08215d22-8bf5-4a00-a331-8e26cd21c290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$122.00'])[1]/following::a[2]</value>
      <webElementGuid>94cbe8d2-96cd-4cfe-a6a1-3bf628ef7e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$242.00'])[1]/preceding::a[1]</value>
      <webElementGuid>1507927a-9ba9-4a5d-84af-d8848eb770e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ex Tax: $200.00'])[1]/preceding::a[1]</value>
      <webElementGuid>ebfd0693-450b-44f9-b219-0a47d00a2132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Samsung SyncMaster 941BW']/parent::*</value>
      <webElementGuid>48946a39-79c8-4924-ad95-c2db1adc0f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://localhost/opencart41/upload/index.php?route=product/product&amp;language=en-gb&amp;product_id=33&amp;path=25_28'])[2]</value>
      <webElementGuid>e8a9fa36-80ba-4af9-92e7-49ee35f6cd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/h4/a</value>
      <webElementGuid>2681a57a-d37e-4e82-9823-d0c22b2e40b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/opencart41/upload/index.php?route=product/product&amp;language=en-gb&amp;product_id=33&amp;path=25_28' and (text() = 'Samsung SyncMaster 941BW' or . = 'Samsung SyncMaster 941BW')]</value>
      <webElementGuid>2050dfa8-2014-4347-b05a-d4454888abd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
