<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your coupon here_coupon</name>
   <tag></tag>
   <elementGuidId>779ad741-522a-47f8-98d3-40d4422a7e0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-coupon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-coupon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your coupon here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9177db5c-96db-486b-9fb9-998016e81187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56af49ef-15d5-4990-ba05-dcbf031f37fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>coupon</value>
      <webElementGuid>dc9285c1-9110-45f5-bd73-f045d4bc8df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your coupon here</value>
      <webElementGuid>751bfe08-aa55-4666-bbcc-8f966a158f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-coupon</value>
      <webElementGuid>bed4821e-8dea-410f-8835-c56686e34f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7471d17f-d81d-4c01-a138-ed3fd76a039b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-coupon&quot;)</value>
      <webElementGuid>76cb38c2-6072-4597-95e2-5ecfda31954d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-coupon']</value>
      <webElementGuid>2e653d26-235d-4da6-8e7e-9edc177f69bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-coupon']/div/div/input</value>
      <webElementGuid>f8ee0102-3d0c-4c7d-8d74-f00cb5884b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/div/input</value>
      <webElementGuid>7f9b4eef-8004-46c6-8b0f-9200dc15063e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'coupon' and @placeholder = 'Enter your coupon here' and @id = 'input-coupon']</value>
      <webElementGuid>3ae85cd8-cae5-47d8-b683-6ca05c5dccd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
