<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Post Code_shipping_postcode</name>
   <tag></tag>
   <elementGuidId>48e8b675-40c8-4287-96ba-87ac8414c298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-shipping-postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-shipping-postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Post Code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>820724b8-2dcd-438f-abd9-cdc5f3525652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89b2c7c8-0488-467e-82f5-cd9f2564bfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_postcode</value>
      <webElementGuid>567b4f11-5c5f-41e5-a4bf-2b0758017c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Post Code</value>
      <webElementGuid>0afd7dba-78d4-4db6-93ef-31e81b25847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-shipping-postcode</value>
      <webElementGuid>9b3a3217-c638-4258-90f7-1c248a131f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b53b874e-4983-49da-bd90-a960d108c6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-shipping-postcode&quot;)</value>
      <webElementGuid>9c355074-bead-4446-a4b4-51ab5419382f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-shipping-postcode']</value>
      <webElementGuid>5817060b-f8db-49a9-b95d-ea8a6f1af886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='shipping-address']/div/div[5]/input</value>
      <webElementGuid>690ec057-42a1-434b-8afe-fb10891a9b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>1b47e5f3-bafd-40c1-a165-6392145a41ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'shipping_postcode' and @placeholder = 'Post Code' and @id = 'input-shipping-postcode']</value>
      <webElementGuid>c275a22e-44a6-45eb-b35b-42b639bb5930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
