<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_shipping_city</name>
   <tag></tag>
   <elementGuidId>a5fc4789-569c-47c4-9b10-4d91205a657a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-shipping-city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-shipping-city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;City&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66173b15-744b-4fd4-a666-5b9a153ca1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2170c1a1-d891-4b8e-a875-4c099598114a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_city</value>
      <webElementGuid>e2f53cdc-b8ac-4cce-b201-6b12441f08ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>e210ebc4-2567-4c16-8570-16cff4665580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-shipping-city</value>
      <webElementGuid>a9b3a921-cdc9-42ea-a8da-5ddfd4ef75c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f56008fb-d7c1-4727-9ad5-cbc2f099e46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-shipping-city&quot;)</value>
      <webElementGuid>79e23f95-1861-42ee-b13a-230cb51d7036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-shipping-city']</value>
      <webElementGuid>e9cd3a06-3679-466d-be6d-8e98560e82c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='shipping-address']/div/div[4]/input</value>
      <webElementGuid>d6faf4b9-a914-4020-82fd-726370d25260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b3176ea7-2a35-4c4b-807f-e2944c19357b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'shipping_city' and @placeholder = 'City' and @id = 'input-shipping-city']</value>
      <webElementGuid>31c3720a-cb05-4740-877a-b5fcd4335d49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
