<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- Avtonomna Resp_d70280</name>
   <tag></tag>
   <elementGuidId>2a19fc18-d294-4855-8e72-e3dd6f22e732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-shipping-zone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-shipping-zone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Region / State&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f570d609-660b-497f-89ff-f2de924d0c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_zone_id</value>
      <webElementGuid>2841948d-813d-49a7-b889-0d03aed2c881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-shipping-zone</value>
      <webElementGuid>24114453-1579-4ca3-a3a2-435a38de7d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>709d8d57-4831-4f28-9e65-f9152e426c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oc-value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9c7f251c-fb4f-493b-a5c7-1df1ab2c5ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- Avtonomna Respublika KrymCherkaskaChernihivskaChernivetskaDnipropetrovskaDonetskaIvano-FrankivskaKharkivskaKhersonskaKhmelnytskaKirovohradskaKyivKyivskaLuhanskaLvivskaMykolaivskaOdeskaPoltavskaRivnenskaSevastopolSumskaTernopilskaVinnytskaVolynskaZakarpatskaZaporizkaZhytomyrskа</value>
      <webElementGuid>a645f89e-4d1b-4376-9c36-1e46f7ade69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-shipping-zone&quot;)</value>
      <webElementGuid>80a9cb53-0e6d-4495-85e3-ffbbc47da7a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input-shipping-zone']</value>
      <webElementGuid>76b3632e-a7d5-43ac-86ea-477a84ab099d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='shipping-address']/div/div[7]/select</value>
      <webElementGuid>17e956ac-a9cd-4265-a384-26816effcd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State'])[1]/following::select[1]</value>
      <webElementGuid>b4c00da2-7e3c-4cc6-a0cb-d0fbaf2e7482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>40c488d1-8d59-4dc8-af9e-369b5916c618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Password'])[1]/preceding::select[1]</value>
      <webElementGuid>e3b5b245-8efe-4874-a032-a2f9e6d66202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::select[1]</value>
      <webElementGuid>038ed0ac-2763-490d-8caa-d95410aeef44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>c83491ed-2484-4704-9aa9-bf7d422d9896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'shipping_zone_id' and @id = 'input-shipping-zone' and (text() = ' --- Please Select --- Avtonomna Respublika KrymCherkaskaChernihivskaChernivetskaDnipropetrovskaDonetskaIvano-FrankivskaKharkivskaKhersonskaKhmelnytskaKirovohradskaKyivKyivskaLuhanskaLvivskaMykolaivskaOdeskaPoltavskaRivnenskaSevastopolSumskaTernopilskaVinnytskaVolynskaZakarpatskaZaporizkaZhytomyrskа' or . = ' --- Please Select --- Avtonomna Respublika KrymCherkaskaChernihivskaChernivetskaDnipropetrovskaDonetskaIvano-FrankivskaKharkivskaKhersonskaKhmelnytskaKirovohradskaKyivKyivskaLuhanskaLvivskaMykolaivskaOdeskaPoltavskaRivnenskaSevastopolSumskaTernopilskaVinnytskaVolynskaZakarpatskaZaporizkaZhytomyrskа')]</value>
      <webElementGuid>3d31a0fb-2ef0-410f-9eba-d157ecd4cf59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
