<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- FunafutiNanuma_ecf7aa</name>
   <tag></tag>
   <elementGuidId>9aed9fb4-ee18-455e-8024-a66efad0b6a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-shipping-zone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-shipping-zone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Region / State&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5a62e3ce-6426-4ddc-84c7-829506efcd82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_zone_id</value>
      <webElementGuid>307b5752-a38d-4b52-9620-1086b9d84ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-shipping-zone</value>
      <webElementGuid>8200bbee-3b1f-4639-b7a2-4630f29b4f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>796ec696-0d27-49f8-9c16-ccad392c7191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oc-value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3d7e8f7f-fe46-4e7c-b5b9-0c598655f4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- FunafutiNanumangaNanumeaNiulakitaNiutaoNuiNukufetauNukulaelaeVaitupu</value>
      <webElementGuid>31ae9328-342a-4ec8-bcfb-c2637580477a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-shipping-zone&quot;)</value>
      <webElementGuid>a510e75f-cb0a-4f62-8b78-a1fc9b167c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input-shipping-zone']</value>
      <webElementGuid>0afe48de-54f7-4b72-bb63-d632271793ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='shipping-address']/div/div[7]/select</value>
      <webElementGuid>1afc9549-c330-40ce-82ab-0e59e9b4d4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State'])[1]/following::select[1]</value>
      <webElementGuid>9d840dfb-2692-42b4-bc82-1c7d92ebaf6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>b11c736e-a3f7-466e-9511-f5d6c337e025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Password'])[1]/preceding::select[1]</value>
      <webElementGuid>32efedc5-0ab8-480a-9343-ae5e48d05d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::select[1]</value>
      <webElementGuid>0e5ef366-128b-404c-b9c5-901fe3ceeb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>d7093474-8b85-404b-bdd7-9958e2284dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'shipping_zone_id' and @id = 'input-shipping-zone' and (text() = ' --- Please Select --- FunafutiNanumangaNanumeaNiulakitaNiutaoNuiNukufetauNukulaelaeVaitupu' or . = ' --- Please Select --- FunafutiNanumangaNanumeaNiulakitaNiutaoNuiNukufetauNukulaelaeVaitupu')]</value>
      <webElementGuid>65824e33-ad90-48fe-bf64-2c5bb3c26400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
